version: '3.8'

services:
  tams-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - ./ml_models:/app/ml_models
    restart: unless-stopped

  # Optional: Add a simple frontend for testing
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./frontend:/usr/share/nginx/html
  #   depends_on:
  #     - tams-api
